{{- define "common-templates.secrets" -}}
{{- range $index, $secret := .Values.secrets }}

---

apiVersion: v1
kind: Secret
metadata:
  {{- range $key, $value := $secret.metadata }}
    {{- if or (eq $key "resourceVersion") (eq $key "creationTimestamp") }}
    {{ $key }}: "{{ $value }}"
    {{- else if eq $key "annotations" }}
    kubectl.kubernetes.io/last-applied-configuration: {{  toJson $value  }}
    {{- else }}
    {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
type: {{ $secret.type }}
data:
  {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value }}
  {{- end }}

{{- end }}
{{- end -}}