persistentVolumeClaims:
  - metadata:
      name: postgres-pvc
    spec:
      volumeName: postgres-pv #Claim by name
      accessModes:
        - ReadWriteOnce
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi #Request 1Gi to 5Gi, depending of the number of claims and the size of of them

